// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAi6M6VZKeBth4i-U8aS7bg13NlzF36w8',
    appId: '1:589555525545:web:da28ee21836446deae86b8',
    messagingSenderId: '589555525545',
    projectId: 'snapconnect-bodymod',
    authDomain: 'snapconnect-bodymod.firebaseapp.com',
    storageBucket: 'snapconnect-bodymod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA01gXxD11cCoe_4jmeQ26ub9y09I2yQn0',
    appId: '1:589555525545:android:a0c690196d0a872dae86b8',
    messagingSenderId: '589555525545',
    projectId: 'snapconnect-bodymod',
    storageBucket: 'snapconnect-bodymod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MJFGSA-4wdQX2kZFH3rV6Bhat8mxxVQ',
    appId: '1:589555525545:ios:450548851894f992ae86b8',
    messagingSenderId: '589555525545',
    projectId: 'snapconnect-bodymod',
    storageBucket: 'snapconnect-bodymod.firebasestorage.app',
    iosBundleId: 'com.example.snapconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-MJFGSA-4wdQX2kZFH3rV6Bhat8mxxVQ',
    appId: '1:589555525545:ios:450548851894f992ae86b8',
    messagingSenderId: '589555525545',
    projectId: 'snapconnect-bodymod',
    storageBucket: 'snapconnect-bodymod.firebasestorage.app',
    iosBundleId: 'com.example.snapconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAi6M6VZKeBth4i-U8aS7bg13NlzF36w8',
    appId: '1:589555525545:web:3a23b9a8c73ffa9cae86b8',
    messagingSenderId: '589555525545',
    projectId: 'snapconnect-bodymod',
    authDomain: 'snapconnect-bodymod.firebaseapp.com',
    storageBucket: 'snapconnect-bodymod.firebasestorage.app',
  );
}
